name: pr3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  path_provider: ^2.1.4
  flutter_slidable: ^3.1.1
  supabase_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/components/product.json
    - lib/components/images/placeholder.png
    - lib/components/images/profile.png
  uses-material-design: true
